name: CI/CD Pipeline

on:
  workflow_call:
    secrets:
      VITE_RPC_HTTP_ENDPOINT:
        required: true
      PUBLISH_DOCS_TOKEN:
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-build-deploy:
    name: Lint, Build, and Deploy
    runs-on: ubuntu-latest
    container:
      image: jarredsumner/bun:edge # Official Docker image for Bun
    permissions:
      contents: write # Grants write access to the repository content
      pages: write    # Grants write access to GitHub Pages
      id-token: write # Optional, for OIDC authentication
    env:
      NODE_ENV: production
      VITE_RPC_HTTP_ENDPOINT: ${{ secrets.VITE_RPC_HTTP_ENDPOINT }}
      VITE_SOLSCAN_TX_URL: https://solscan.io/tx/__HASH__?cluster=devnet

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run linter
      - name: Run linter
        run: bun format & bun lint

      # Build the application
      - name: Build application
        run: bun build

      - name: Deploy to latest directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935
        with:
          # This `PUBLISH_DOCS_TOKEN` needs to be manually set per-repository.
          # Look in the repository settings under "Environments", and set this token in the `github-pages` environment.
          personal_token: ${{ secrets.PUBLISH_DOCS_TOKEN }}
          publish_dir: ./dist
          destination_dir: latest
